# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  jupynium = {
    pname = "jupynium";
    version = "0.2.7";
    src = fetchurl {
      url = "https://pypi.org/packages/source/j/jupynium/jupynium-0.2.7.tar.gz";
      sha256 = "sha256-fZtSND4uy5vja09a4ZshFElZIdonNzxAZIqXQABrPUM=";
    };
  };
  valkey-glide = {
    pname = "valkey-glide";
    version = "2.3.0";
    src = fetchurl {
      url = "https://pypi.org/packages/source/v/valkey-glide/valkey_glide-2.3.0.tar.gz";
      sha256 = "sha256-I/i5yikE9hTzYa+QVyJ0SU/wV0pZ7sKfP7O8T9+z5BQ=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-I_i5yikE9hTzYa+QVyJ0SU_wV0pZ7sKfP7O8T9+z5BQ=/Cargo.lock";
      outputHashes = {
        
      };
    };
  };
  version-pioneer = {
    pname = "version-pioneer";
    version = "0.0.16";
    src = fetchurl {
      url = "https://pypi.org/packages/source/v/version_pioneer/version_pioneer-0.0.16.tar.gz";
      sha256 = "sha256-AdJ90fhZraBxc7dU1ckpB0TtBE56dZWaPXpFjwgRvKg=";
    };
  };
  virtualsmartcard = {
    pname = "virtualsmartcard";
    version = "virtualsmartcard-0.10";
    src = fetchFromGitHub {
      owner = "frankmorgner";
      repo = "vsmartcard";
      rev = "virtualsmartcard-0.10";
      fetchSubmodules = false;
      sha256 = "sha256-+BrX2aqByUvIUbN4K+sdq9bH29FD2rtTt4q+URPgx7A=";
    };
  };
}
