# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  jupynium = {
    pname = "jupynium";
    version = "0.2.7";
    src = fetchurl {
      url = "https://pypi.org/packages/source/j/jupynium/jupynium-0.2.7.tar.gz";
      sha256 = "sha256-fZtSND4uy5vja09a4ZshFElZIdonNzxAZIqXQABrPUM=";
    };
  };
  valkey-glide = {
    pname = "valkey-glide";
    version = "2.2.7";
    src = fetchurl {
      url = "https://pypi.org/packages/source/v/valkey-glide/valkey_glide-2.2.7.tar.gz";
      sha256 = "sha256-LNBbjIcceHjLiWeaw08pTxAEgbZPedeXzeMlodBRzck=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-LNBbjIcceHjLiWeaw08pTxAEgbZPedeXzeMlodBRzck=/Cargo.lock";
      outputHashes = {

      };
    };
  };
  version-pioneer = {
    pname = "version-pioneer";
    version = "0.0.15";
    src = fetchurl {
      url = "https://pypi.org/packages/source/v/version_pioneer/version_pioneer-0.0.15.tar.gz";
      sha256 = "sha256-QeAgZ6ISf4HLf8/EY7yowl4y7HlXuI9b2oHouihayWk=";
    };
  };
  virtualsmartcard = {
    pname = "virtualsmartcard";
    version = "virtualsmartcard-0.10";
    src = fetchFromGitHub {
      owner = "frankmorgner";
      repo = "vsmartcard";
      rev = "virtualsmartcard-0.10";
      fetchSubmodules = false;
      sha256 = "sha256-+BrX2aqByUvIUbN4K+sdq9bH29FD2rtTt4q+URPgx7A=";
    };
  };
}
