# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchurl,
}:
{
  zotero-better-bibtex =
    let
      version = "9.0.19";
    in
    {
      pname = "zotero-better-bibtex";
      inherit version;
      src = fetchurl {
        url = "https://github.com/retorquere/zotero-better-bibtex/releases/download/v${version}/zotero-better-bibtex-${version}.xpi";
        sha256 = "sha256-sfHDfWKQ3+X0gtjCIb+yJGcfSc8TTMk71sCQJ7mC0Xs=";
      };
      addonId = "better-bibtex@iris-advies.com";
      license = "mit";
      homepage = "https://github.com/retorquere/zotero-better-bibtex";
      description = "Make Zotero effective for us LaTeX holdouts";
    };
  zotero-pdf-translate =
    let
      version = "2.4.3";
    in
    {
      pname = "zotero-pdf-translate";
      inherit version;
      src = fetchurl {
        url = "https://github.com/windingwind/zotero-pdf-translate/releases/download/v${version}/translate-for-zotero.xpi";
        sha256 = "sha256-/EHaAKXQBg1F5l8URsiVg+GGxQBmpLLpCML+Y0wmM3I=";
      };
      addonId = "zoteropdftranslate@euclpts.com";
      license = "agpl3Only";
      homepage = "https://github.com/winidngwind/zotero-pdf-translate";
      description = "Translate PDF, EPub, webpage, metadata, annotations, notes to the target language. Support 20+ translate services.";
    };
  zotero-reading-list =
    let
      version = "1.5.17";
    in
    {
      pname = "zotero-reading-list";
      inherit version;
      src = fetchurl {
        url = "https://github.com/Dominic-DallOsto/zotero-reading-list/releases/download/v${version}/zotero-reading-list.xpi";
        sha256 = "sha256-tNe2qbMtpk65jvLenJc4XAfsNQhahRkUyw2ajQdVvfA=";
      };
      addonId = "reading-list@hotmail.com";
      license = "gpl3";
      homepage = "https://github.com/Dominic-DallOsto/zotero-reading-list";
      description = "Keep track of whether you've read items in Zotero";
    };
  zotero-scipdf =
    let
      version = "8.0.4";
    in
    {
      pname = "zotero-scipdf";
      inherit version;
      src = fetchurl {
        url = "https://github.com/syt2/zotero-scipdf/releases/download/V${version}/sci-pdf.xpi";
        sha256 = "sha256-LWZHzH8mMKeJt+nExKgZIqva9sR45454KwOwxT6YPlY=";
      };
      addonId = "scipdf@ytshen.com";
      license = "agpl3Plus";
      homepage = "https://github.com/syt2/zotero-scipdf";
      description = "Download PDF from Sci-Hub automatically (For Zotero7)";
    };
  zotero-zotmoov =
    let
      version = "1.2.26";
    in
    {
      pname = "zotero-zotmoov";
      inherit version;
      src = fetchurl {
        url = "https://github.com/wileyyugioh/zotmoov/releases/download/${version}/zotmoov-${version}-fx.xpi";
        sha256 = "sha256-y89Pun0exbMa+Wq7BPdaBSkMtqmi3nHS5AH/qAuiyi4=";
      };
      addonId = "zotmoov@wileyy.com";
      license = "gpl3Only";
      homepage = "https://github.com/wileyyugioh/zotmoov";
      description = "Mooves attachments and links them";
    };
}
