# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchurl,
}:
{
  zotero-better-bibtex =
    let
      version = "9.0.63";
    in
    {
      pname = "zotero-better-bibtex";
      inherit version;
      src = fetchurl {
        url = "https://github.com/retorquere/zotero-better-bibtex/releases/download/v${version}/zotero-better-bibtex-${version}.xpi";
        sha256 = "sha256-Ok0IDslBU6jCS/gnVonF+UbZnjFLauD6tQYNaXD1Y4g=";
      };
      addonId = "better-bibtex@iris-advies.com";
      license = "mit";
      homepage = "https://github.com/retorquere/zotero-better-bibtex";
      description = "Make Zotero effective for us LaTeX holdouts";
    };
  zotero-pdf-translate =
    let
      version = "2.4.7";
    in
    {
      pname = "zotero-pdf-translate";
      inherit version;
      src = fetchurl {
        url = "https://github.com/windingwind/zotero-pdf-translate/releases/download/v${version}/translate-for-zotero.xpi";
        sha256 = "sha256-DLJn7s/wTSzjlAHlRY4xMSQi13rEYPaVjJouLaEJLdI=";
      };
      addonId = "zoteropdftranslate@euclpts.com";
      license = "agpl3Only";
      homepage = "https://github.com/winidngwind/zotero-pdf-translate";
      description = "Translate PDF, EPub, webpage, metadata, annotations, notes to the target language. Support 20+ translate services.";
    };
  zotero-reading-list =
    let
      version = "1.5.17";
    in
    {
      pname = "zotero-reading-list";
      inherit version;
      src = fetchurl {
        url = "https://github.com/Dominic-DallOsto/zotero-reading-list/releases/download/v${version}/zotero-reading-list.xpi";
        sha256 = "sha256-tNe2qbMtpk65jvLenJc4XAfsNQhahRkUyw2ajQdVvfA=";
      };
      addonId = "reading-list@hotmail.com";
      license = "gpl3";
      homepage = "https://github.com/Dominic-DallOsto/zotero-reading-list";
      description = "Keep track of whether you've read items in Zotero";
    };
  zotero-scipdf =
    let
      version = "8.1.0";
    in
    {
      pname = "zotero-scipdf";
      inherit version;
      src = fetchurl {
        url = "https://github.com/syt2/zotero-scipdf/releases/download/V${version}/sci-pdf.xpi";
        sha256 = "sha256-uGzS/QCA9COtknCOhp3jShtIGQHkZo/10Tr3tFFxWjM=";
      };
      addonId = "scipdf@ytshen.com";
      license = "agpl3Plus";
      homepage = "https://github.com/syt2/zotero-scipdf";
      description = "Download PDF from Sci-Hub automatically (For Zotero7)";
      updateOptions = [
        "--version-regex"
        "V(.*)"
      ];
    };
  zotero-zotmoov =
    let
      version = "1.2.32";
    in
    {
      pname = "zotero-zotmoov";
      inherit version;
      src = fetchurl {
        url = "https://github.com/wileyyugioh/zotmoov/releases/download/${version}/zotmoov-${version}-fx.xpi";
        sha256 = "sha256-d3DcLGLSqqsmYv10Aq+t0Fg4e/9pV4SBrAOb/AUOzCs=";
      };
      addonId = "zotmoov@wileyy.com";
      license = "gpl3Only";
      homepage = "https://github.com/wileyyugioh/zotmoov";
      description = "Mooves attachments and links them";
    };
}
