# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchurl,
}:
{
  zotero-better-bibtex =
    let
      version = "9.0.19";
    in
    {
      pname = "zotero-better-bibtex";
      inherit version;
      src = fetchurl {
        url = "https://github.com/retorquere/zotero-better-bibtex/releases/download/v${version}/zotero-better-bibtex-${version}.xpi";
        sha256 = "sha256-sfHDfWKQ3+X0gtjCIb+yJGcfSc8TTMk71sCQJ7mC0Xs=";
      };
      addonId = "better-bibtex@iris-advies.com";
      license = "mit";
      homepage = "https://github.com/retorquere/zotero-better-bibtex";
      description = "Make Zotero effective for us LaTeX holdouts";
    };
  zotero-night =
    let
      version = "0.4.23";
    in
    {
      pname = "zotero-night";
      inherit version;
      src = fetchurl {
        url = "https://github.com/tefkah/zotero-night/releases/download/v${version}/night.xpi";
        sha256 = "sha256-szoKwmYMm9fZrWxqN2ZJptahCgGkIUNwR0n3m5zhiJw=";
      };
      addonId = "night@tefkah.com";
      license = "gpl3";
      homepage = "https://github.com/tefkah/zotero";
      description = "Night theme for Zotero UI and PDF";
    };
  zotero-pdf-translate =
    let
      version = "2.4.3";
    in
    {
      pname = "zotero-pdf-translate";
      inherit version;
      src = fetchurl {
        url = "https://github.com/windingwind/zotero-pdf-translate/releases/download/v${version}/translate-for-zotero.xpi";
        sha256 = "sha256-/EHaAKXQBg1F5l8URsiVg+GGxQBmpLLpCML+Y0wmM3I=";
      };
      addonId = "zoteropdftranslate@euclpts.com";
      license = "agpl3Only";
      homepage = "https://github.com/winidngwind/zotero-pdf-translate";
      description = "Translate PDF, EPub, webpage, metadata, annotations, notes to the target language. Support 20+ translate services.";
    };
  zotero-reading-list =
    let
      version = "1.5.17";
    in
    {
      pname = "zotero-reading-list";
      inherit version;
      src = fetchurl {
        url = "https://github.com/Dominic-DallOsto/zotero-reading-list/releases/download/v${version}/zotero-reading-list.xpi";
        sha256 = "sha256-tNe2qbMtpk65jvLenJc4XAfsNQhahRkUyw2ajQdVvfA=";
      };
      addonId = "reading-list@hotmail.com";
      license = "gpl3";
      homepage = "https://github.com/Dominic-DallOsto/zotero-reading-list";
      description = "Keep track of whether you've read items in Zotero";
    };
  zotero-scipdf =
    let
      version = "8.0.4";
    in
    {
      pname = "zotero-scipdf";
      inherit version;
      src = fetchurl {
        url = "https://github.com/syt2/zotero-scipdf/releases/download/V${version}/sci-pdf.xpi";
        sha256 = "sha256-LWZHzH8mMKeJt+nExKgZIqva9sR45454KwOwxT6YPlY=";
      };
      addonId = "scipdf@ytshen.com";
      license = "agpl3Plus";
      homepage = "https://github.com/syt2/zotero-scipdf";
      description = "Download PDF from Sci-Hub automatically (For Zotero7)";
    };
  zotero-zotfile =
    let
      version = "5.1.2";
    in
    {
      pname = "zotero-zotfile";
      inherit version;
      src = fetchurl {
        url = "https://github.com/jlegewie/zotfile/releases/download/v${version}/zotfile-${version}-fx.xpi";
        sha256 = "sha256-vmJVLqNgxbI6eE3TqDKJs/u/Bdemag2aADfy8L89YKc=";
      };
      addonId = "zotfile@columbia.edu";
      license = "gpl3";
      homepage = "https://github.com/jlegewie/zotfile";
      description = "Zotero plugin to manage your attachments: automatically rename, move, and attach PDFs (or other files) to Zotero items, sync PDFs from your Zotero library to your (mobile) PDF reader (e.g. an iPad, Android tablet, etc.), and extract PDF annotations.";
    };
  zotero-zotmoov =
    let
      version = "1.2.26";
    in
    {
      pname = "zotero-zotmoov";
      inherit version;
      src = fetchurl {
        url = "https://github.com/wileyyugioh/zotmoov/releases/download/${version}/zotmoov-${version}-fx.xpi";
        sha256 = "sha256-y89Pun0exbMa+Wq7BPdaBSkMtqmi3nHS5AH/qAuiyi4=";
      };
      addonId = "zotmoov@wileyy.com";
      license = "gpl3Only";
      homepage = "https://github.com/wileyyugioh/zotmoov";
      description = "Mooves attachments and links them";
    };
}
