# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  doq = {
    pname = "doq";
    version = "0.9.1";
    src = fetchurl {
      url = "https://pypi.io/packages/source/d/doq/doq-0.9.1.tar.gz";
      sha256 = "sha256-uszDSN35Z8i/Mr/fVNqDJuHcdPN4ZeLBdgEq0Lx+6h4=";
    };
  };
  droidcam-obs-plugin = {
    pname = "droidcam-obs-plugin";
    version = "1.6.0";
    src = fetchgit {
      url = "https://github.com/dev47apps/droidcam-obs-plugin";
      rev = "1.6.0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-ILvZMwrBZvLLj+wcMIT9vOODWlSuAQ/AdxaGhqjYdyA=";
    };
  };
  fcitx5-nord = {
    pname = "fcitx5-nord";
    version = "bdaa8fb723b8d0b22f237c9a60195c5f9c9d74d1";
    src = fetchFromGitHub ({
      owner = "tonyfettes";
      repo = "fcitx5-nord";
      rev = "bdaa8fb723b8d0b22f237c9a60195c5f9c9d74d1";
      fetchSubmodules = false;
      sha256 = "sha256-qVo/0ivZ5gfUP17G29CAW0MrRFUO0KN1ADl1I/rvchE=";
    });
  };
  flake-asusctl = {
    pname = "flake-asusctl";
    version = "4.5.7";
    src = fetchgit {
      url = "https://gitlab.com/asus-linux/asusctl";
      rev = "4.5.7";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-43oAW7mP+ZKYNGthm305cAJblWDEJH5ApuUE7Bw/+6s=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./flake-asusctl-4.5.7/Cargo.lock;
      outputHashes = {
        "supergfxctl-5.0.2" = "sha256-zp92mWyWUEWUP4kEyHbiUyYTtp2kLv+gxkPzOu77fi8=";
        "ecolor-0.20.0" = "sha256-tnjFkaCWmCPGw3huQN9VOAeiH+zk3Zk9xYoRKmg2WQg=";
        "notify-rust-4.6.0" = "sha256-jhCgisA9f6AI9e9JQUYRtEt47gQnDv5WsdRKFoKvHJs=";
      };
    };
  };
  flake-supergfxctl = {
    pname = "flake-supergfxctl";
    version = "5.0.1";
    src = fetchgit {
      url = "https://gitlab.com/asus-linux/supergfxctl";
      rev = "5.0.1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-4q+7F8s6y+oDkBUKIBBsXZ2EtADcChdnjmABjBUnH9k=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./flake-supergfxctl-5.0.1/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
  knp = {
    pname = "knp";
    version = "25425d33907ce69c5fa5b584ba58183020a07bba";
    src = fetchFromGitHub ({
      owner = "ku-nlp";
      repo = "knp";
      rev = "25425d33907ce69c5fa5b584ba58183020a07bba";
      fetchSubmodules = false;
      sha256 = "sha256-P33+6Iwh7fYugZrFRylrtzz24EjwUToXJ/nbDw06Pbg=";
    });
  };
  notify-rust = {
    pname = "notify-rust";
    version = "c83082a2549932bde52a4ec449b9981fc39e9a0d";
    src = fetchFromGitHub ({
      owner = "flukejones";
      repo = "notify-rust";
      rev = "c83082a2549932bde52a4ec449b9981fc39e9a0d";
      fetchSubmodules = false;
      sha256 = "sha256-jhCgisA9f6AI9e9JQUYRtEt47gQnDv5WsdRKFoKvHJs=";
    });
  };
  pyknp = {
    pname = "pyknp";
    version = "0.6.1";
    src = fetchurl {
      url = "https://pypi.io/packages/source/p/pyknp/pyknp-0.6.1.tar.gz";
      sha256 = "sha256-X8ooinAwTHRdINpWV8YXW16t96elce1PV7sVfrbn300=";
    };
  };
  snack = {
    pname = "snack";
    version = "2.2.10";
    src = fetchurl {
      url = "http://www.speech.kth.se/snack/dist/snack2.2.10.tar.gz";
      sha256 = "sha256-S/52RUerkrpY9Dt3Nm27fHs1EtZaJ82/nlhanLZM6B4=";
    };
  };
  wavesurfer = {
    pname = "wavesurfer";
    version = "1.8.8p5";
    src = fetchurl {
      url = "http://downloads.sourceforge.net/wavesurfer/wavesurfer-1.8.8p5-src.tgz";
      sha256 = "sha256-rlYGEUfdEXD3SF3JwZ23pF3RVwUKw5RmYsf8ec/7YRo=";
    };
  };
  xp-pen-tablet = {
    pname = "xp-pen-tablet";
    version = "3.2.3.220323";
    src = fetchurl {
      url = "https://www.xp-pen.com/download/file/id/1936/pid/690/ext/gz.html";
      sha256 = "sha256-cLbcE0WVjBhY0JGj1IvddckfzIeboXVznvkVJ5C9yys=";
    };
  };
}
