# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  SpeechRecognition = {
    pname = "SpeechRecognition";
    version = "3.10.0";
    src = fetchurl {
      url = "https://pypi.org/packages/source/S/SpeechRecognition/SpeechRecognition-3.10.0.tar.gz";
      sha256 = "sha256-FBMRVeiougDq0be5saL6cchF5Ntfml9mozob1sVcbDU=";
    };
  };
  asusctl-latest = {
    pname = "asusctl-latest";
    version = "4.6.2";
    src = fetchgit {
      url = "https://gitlab.com/asus-linux/asusctl";
      rev = "4.6.2";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-qfl8MUSHjqlSnsaudoRD9fY5TM9zgy7L7DA+pctn/nc=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./asusctl-latest-4.6.2/Cargo.lock;
      outputHashes = {
        "supergfxctl-5.1.1" = "sha256-AThaZ9dp5T/DtLPE6gZ9qgkw0xksiq+VCL9Y4G41voE=";
        "ecolor-0.21.0" = "sha256-m7eHX6flwO21umtx3dnIuVUnNsEs3ZCyOk5Vvp/lVfI=";
        "notify-rust-4.6.0" = "sha256-jhCgisA9f6AI9e9JQUYRtEt47gQnDv5WsdRKFoKvHJs=";
      };
    };
  };
  bt-dualboot = {
    pname = "bt-dualboot";
    version = "1.0.1";
    src = fetchurl {
      url = "https://pypi.org/packages/source/b/bt-dualboot/bt-dualboot-1.0.1.tar.gz";
      sha256 = "sha256-pjzGvLkotQllzyrnxqDIjGlpBOvUPkWpv0eooCUrgv8=";
    };
  };
  csharp-ls = {
    pname = "csharp-ls";
    version = "0.8.0";
    src = fetchurl {
      url = "https://www.nuget.org/api/v2/package/csharp-ls/0.8.0";
      sha256 = "sha256-F3N6ESE/VmQA5sOMm3eqSkhSNVCCsnAXTCC+McsAnQw=";
    };
  };
  cups-brother-hll5100dn-cupswrapper = {
    pname = "cups-brother-hll5100dn-cupswrapper";
    version = "3.5.1-1";
    src = fetchurl {
      url = "https://download.brother.com/welcome/dlf102554/hll5100dncupswrapper-3.5.1-1.i386.deb";
      sha256 = "sha256-i309lhjE6FTNd8f0d4vv7/oaNUt165scU9Gzlff8gcE=";
    };
  };
  cups-brother-hll5100dn-lpr = {
    pname = "cups-brother-hll5100dn-lpr";
    version = "3.5.1-1";
    src = fetchurl {
      url = "https://download.brother.com/welcome/dlf102553/hll5100dnlpr-3.5.1-1.i386.deb";
      sha256 = "sha256-JnPiBVJ+ZJKivjq+Kizcf5U8vilOFdLVWBuRUiWJ5zE=";
    };
  };
  doq = {
    pname = "doq";
    version = "0.9.1";
    src = fetchurl {
      url = "https://pypi.org/packages/source/d/doq/doq-0.9.1.tar.gz";
      sha256 = "sha256-uszDSN35Z8i/Mr/fVNqDJuHcdPN4ZeLBdgEq0Lx+6h4=";
    };
  };
  droidcam-obs-plugin = {
    pname = "droidcam-obs-plugin";
    version = "2.1.0";
    src = fetchurl {
      url = "https://github.com/dev47apps/droidcam-obs-plugin/releases/download/2.1.0/droidcam_obs_2.1.0_linux_ffmpeg5.zip";
      sha256 = "sha256-Qrb23aNddJhMvLgRyW7UamDVAjrhZhw4Kbr0FP/5mXs=";
    };
  };
  fcitx5-mozc-ext-neologd = {
    pname = "fcitx5-mozc-ext-neologd";
    version = "1882e33b61673b66d63277f82b4c80ae4e506c10";
    src = fetchFromGitHub {
      owner = "fcitx";
      repo = "mozc";
      rev = "1882e33b61673b66d63277f82b4c80ae4e506c10";
      fetchSubmodules = false;
      sha256 = "sha256-R+w0slVFpqtt7PIr1pyupJjRoQsABVZiMdZ9fKGKAqw=";
    };
  };
  fcitx5-nord = {
    pname = "fcitx5-nord";
    version = "bdaa8fb723b8d0b22f237c9a60195c5f9c9d74d1";
    src = fetchFromGitHub {
      owner = "tonyfettes";
      repo = "fcitx5-nord";
      rev = "bdaa8fb723b8d0b22f237c9a60195c5f9c9d74d1";
      fetchSubmodules = false;
      sha256 = "sha256-qVo/0ivZ5gfUP17G29CAW0MrRFUO0KN1ADl1I/rvchE=";
    };
    date = "2021-07-27";
  };
  fcitx5-skk = {
    pname = "fcitx5-skk";
    version = "5.0.15";
    src = fetchFromGitHub {
      owner = "fcitx";
      repo = "fcitx5-skk";
      rev = "5.0.15";
      fetchSubmodules = false;
      sha256 = "sha256-y5GciWJMEFQM8SsqYANXe/SdVq6GEqsfF1yrKKhw0KA=";
    };
  };
  japanese-usege-dictionary = {
    pname = "japanese-usege-dictionary";
    version = "a4a66772e33746b91e99caceecced9a28507e925";
    src = fetchgit {
      url = "https://github.com/hiroyuki-komatsu/japanese-usage-dictionary";
      rev = "a4a66772e33746b91e99caceecced9a28507e925";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-qnWA+lesLo3Odk8gY9UTKQr/YmIn+nCcbtKDjUDobII=";
    };
    date = "2018-07-01";
  };
  jawiki-kana-kanji-dict = {
    pname = "jawiki-kana-kanji-dict";
    version = "32c2137741740888d791be463f8155937e7a8e46";
    src = fetchurl {
      url = "https://raw.githubusercontent.com/tokuhirom/jawiki-kana-kanji-dict/32c2137741740888d791be463f8155937e7a8e46/SKK-JISYO.jawiki";
      sha256 = "sha256-Pl6IeOe4fWuldIbFC8C5zYmME3oftPYYVYiKWaDhZek=";
    };
    date = "2023-06-21";
  };
  juce = {
    pname = "juce";
    version = "7.0.5";
    src = fetchFromGitHub {
      owner = "juce-framework";
      repo = "JUCE";
      rev = "7.0.5";
      fetchSubmodules = false;
      sha256 = "sha256-NRF9oSE04hk6KVSxuUBpP+z+DKRyb6pzBXtz/pLz0/0=";
    };
  };
  knp = {
    pname = "knp";
    version = "5c637eb99d66defa40d586028cd0ed05c6bdd8fe";
    src = fetchFromGitHub {
      owner = "ku-nlp";
      repo = "knp";
      rev = "5c637eb99d66defa40d586028cd0ed05c6bdd8fe";
      fetchSubmodules = false;
      sha256 = "sha256-Jr8a8Pdi0u5ArZmSnwaIgVyHL89SH7ziuNr3N9OFgJQ=";
    };
    date = "2023-02-24";
  };
  mecab-ipadic-neologd = {
    pname = "mecab-ipadic-neologd";
    version = "v0.0.7";
    src = fetchFromGitHub {
      owner = "neologd";
      repo = "mecab-ipadic-neologd";
      rev = "v0.0.7";
      fetchSubmodules = false;
      sha256 = "sha256-6mZ+Wcre0ZTUitso9kQn11um29cdOUaOAbhPgSq7OxU=";
    };
  };
  mozc-dict-jigyosyo = {
    pname = "mozc-dict-jigyosyo";
    version = "202110";
    src = fetchurl {
      url = "https://osdn.net/projects/ponsfoot-aur/storage/mozc/jigyosyo-202110.zip";
      sha256 = "sha256-bI1F/UyrBAnMwcrZff4GDc87jAfnPm2UJqh+itzsOkM=";
    };
  };
  mozc-dict-x-ken-all = {
    pname = "mozc-dict-x-ken-all";
    version = "202110";
    src = fetchurl {
      url = "https://osdn.net/projects/ponsfoot-aur/storage/mozc/x-ken-all-202110.zip";
      sha256 = "sha256-85iKUrxpGdcoSg7wzbmrAn+HZ8ud58uEabEuH7PLavk=";
    };
  };
  mozcdict-ext = {
    pname = "mozcdict-ext";
    version = "1041a9ca03e48b29873d950c9ea19de70fde1139";
    src = fetchgit {
      url = "https://github.com/reasonset/mozcdict-ext";
      rev = "1041a9ca03e48b29873d950c9ea19de70fde1139";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-PnOsR4q4aswgR1dmu/MLBFPYA4RLs5TlUFJc84PO7Pw=";
    };
    date = "2023-02-16";
  };
  notify-rust = {
    pname = "notify-rust";
    version = "c83082a2549932bde52a4ec449b9981fc39e9a0d";
    src = fetchFromGitHub {
      owner = "flukejones";
      repo = "notify-rust";
      rev = "c83082a2549932bde52a4ec449b9981fc39e9a0d";
      fetchSubmodules = false;
      sha256 = "sha256-jhCgisA9f6AI9e9JQUYRtEt47gQnDv5WsdRKFoKvHJs=";
    };
    date = "2022-11-30";
  };
  plemoljp = {
    pname = "plemoljp";
    version = "v1.6.0";
    src = fetchurl {
      url = "https://github.com/yuru7/PlemolJP/releases/download/v1.6.0/PlemolJP_v1.6.0.zip";
      sha256 = "sha256-iQB11qItBWhaoL0+hTkPugFRwiIKHiZJl2xa9BaSw8w=";
    };
  };
  plemoljp-hs = {
    pname = "plemoljp-hs";
    version = "v1.6.0";
    src = fetchurl {
      url = "https://github.com/yuru7/PlemolJP/releases/download/v1.6.0/PlemolJP_HS_v1.6.0.zip";
      sha256 = "sha256-2t6IKpFA2qy0L7HHNneQQUh76DAkkiiujYyFR06tpO4=";
    };
  };
  plemoljp-nf = {
    pname = "plemoljp-nf";
    version = "v1.6.0";
    src = fetchurl {
      url = "https://github.com/yuru7/PlemolJP/releases/download/v1.6.0/PlemolJP_NF_v1.6.0.zip";
      sha256 = "sha256-6mPtfrb6JV970rsQZhWAd9QbhmjjKob/qTIlAdb8GNw=";
    };
  };
  pyknp = {
    pname = "pyknp";
    version = "0.6.1";
    src = fetchurl {
      url = "https://pypi.org/packages/source/p/pyknp/pyknp-0.6.1.tar.gz";
      sha256 = "sha256-X8ooinAwTHRdINpWV8YXW16t96elce1PV7sVfrbn300=";
    };
  };
  ricoh-sp-c260series-ppd = {
    pname = "ricoh-sp-c260series-ppd";
    version = "1.00";
    src = fetchurl {
      url = "http://support.ricoh.com/w/bb/pub_j/dr_ut_d/4101035/4101035832/V100/5205252/sp-c260series-printer-1.00-amd64.deb";
      sha256 = "sha256-aRqpBpYpQnOdAoGe21cBYrkhtRaiBZJTYgVsdN2irEU=";
    };
  };
  skk-emoji-jisyo = {
    pname = "skk-emoji-jisyo";
    version = "v0.0.7";
    src = fetchFromGitHub {
      owner = "uasi";
      repo = "skk-emoji-jisyo";
      rev = "v0.0.7";
      fetchSubmodules = false;
      sha256 = "sha256-cxaRVV5d7zZdhWxq6m+NjA9P9PKZfwiimCToo81yxkY=";
    };
  };
  snack = {
    pname = "snack";
    version = "2.2.10";
    src = fetchurl {
      url = "http://www.speech.kth.se/snack/dist/snack2.2.10.tar.gz";
      sha256 = "sha256-S/52RUerkrpY9Dt3Nm27fHs1EtZaJ82/nlhanLZM6B4=";
    };
  };
  supergfxctl-latest = {
    pname = "supergfxctl-latest";
    version = "fcba63b1a29284fc76da65e60751a33b81380259";
    src = fetchgit {
      url = "https://gitlab.com/asus-linux/supergfxctl";
      rev = "fcba63b1a29284fc76da65e60751a33b81380259";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-H00QHNILEjOtavXdj4Jd+rdLprJpVSlSVV3qkTeknzQ=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./supergfxctl-latest-fcba63b1a29284fc76da65e60751a33b81380259/Cargo.lock;
      outputHashes = {
        
      };
    };
    date = "2023-06-22";
  };
  torch-lightning = {
    pname = "torch-lightning";
    version = "2.0.4";
    src = fetchurl {
      url = "https://pypi.org/packages/source/l/lightning/lightning-2.0.4.tar.gz";
      sha256 = "sha256-9fXtdaZXyqiTEFFZDtAA1GvxuDEa6JuxepYcPymdvzM=";
    };
  };
  udev-gothic = {
    pname = "udev-gothic";
    version = "v1.3.0";
    src = fetchurl {
      url = "https://github.com/yuru7/udev-gothic/releases/download/v1.3.0/UDEVGothic_v1.3.0.zip";
      sha256 = "sha256-SN8g+4d3zeigMrAmOfr9JD5Zvyr8muC0epenb3hHfJI=";
    };
  };
  udev-gothic-nf = {
    pname = "udev-gothic-nf";
    version = "v1.3.0";
    src = fetchurl {
      url = "https://github.com/yuru7/udev-gothic/releases/download/v1.3.0/UDEVGothic_NF_v1.3.0.zip";
      sha256 = "sha256-2H4CbiACo+QJm3GD3pJF1FIw3+c5PtWXvNn1aBwasCk=";
    };
  };
  unityhub-latest = {
    pname = "unityhub-latest";
    version = "3.5.0";
    src = fetchurl {
      url = "https://hub.unity3d.com/linux/repos/deb/pool/main/u/unity/unityhub_amd64/unityhub-amd64-3.5.0.deb";
      sha256 = "sha256-d5TUUhGqchkrCRqJWHEewurjsHxbfZ+5hv9w9Yv2EQ4=";
    };
  };
  vrchat-vpm-cli = {
    pname = "vrchat-vpm-cli";
    version = "0.1.16";
    src = fetchurl {
      url = "https://www.nuget.org/api/v2/package/vrchat.vpm.cli/0.1.16";
      sha256 = "sha256-lchER19pfnkly9cm5D6YanBQuatG6wlqQYFRhFiwpP4=";
    };
  };
  wavesurfer = {
    pname = "wavesurfer";
    version = "1.8.8p5";
    src = fetchurl {
      url = "http://downloads.sourceforge.net/wavesurfer/wavesurfer-1.8.8p5-src.tgz";
      sha256 = "sha256-rlYGEUfdEXD3SF3JwZ23pF3RVwUKw5RmYsf8ec/7YRo=";
    };
  };
  xp-pen-tablet = {
    pname = "xp-pen-tablet";
    version = "3.2.3.230215";
    src = fetchurl {
      url = "https://www.xp-pen.com/download/file/id/1936/pid/690/ext/gz.html";
      sha256 = "sha256-cLbcE0WVjBhY0JGj1IvddckfzIeboXVznvkVJ5C9yys=";
    };
  };
  yaskkserv2 = {
    pname = "yaskkserv2";
    version = "0.1.6";
    src = fetchFromGitHub {
      owner = "wachikun";
      repo = "yaskkserv2";
      rev = "0.1.6";
      fetchSubmodules = false;
      sha256 = "sha256-qVQxkbnk6UXBSZaOEyy7jZhvejHS/FJWqDsBSM1tCpE=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./yaskkserv2-0.1.6/Cargo.lock;
      outputHashes = {
        
      };
    };
  };
}
