# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  prettier-plugin-nginx = {
    pname = "prettier-plugin-nginx";
    version = "b3c840f4bac1373c2dc984825e3dad3308fcbcbe";
    src = fetchFromGitHub {
      owner = "jxddk";
      repo = "prettier-plugin-nginx";
      rev = "b3c840f4bac1373c2dc984825e3dad3308fcbcbe";
      fetchSubmodules = false;
      sha256 = "sha256-JsAgLg89gxLlmXbeoFAceGsmvLLrHuQHA/heuzFxWSg=";
    };
    extract = {
      "package.json" = ./. + "/sha256-JsAgLg89gxLlmXbeoFAceGsmvLLrHuQHA_heuzFxWSg=/package.json";
    };pkgmgr = "npm";
    needGenLock = "yes";
    date = "2023-03-17";
  };
  prettier-plugin-php = {
    pname = "prettier-plugin-php";
    version = "v0.24.0";
    src = fetchFromGitHub {
      owner = "prettier";
      repo = "plugin-php";
      rev = "v0.24.0";
      fetchSubmodules = false;
      sha256 = "sha256-u7cBqZI67/QTBp8YpLOgtZUZt/aJxknjGyT4OSTVZNM=";
    };
    pkgmgr = "yarn";
  };
  prettier-plugin-pug = {
    pname = "prettier-plugin-pug";
    version = "3.4.2";
    src = fetchFromGitHub {
      owner = "prettier";
      repo = "plugin-pug";
      rev = "3.4.2";
      fetchSubmodules = false;
      sha256 = "sha256-4CsKMj8Xnq+dlGzLAG2hV8jTCMYBYhaV/uoKAfztSGs=";
    };
    pkgmgr = "pnpm";
    dontNpmPrune = "yes";
  };
  prettier-plugin-ruby = {
    pname = "prettier-plugin-ruby";
    version = "v4.0.4";
    src = fetchFromGitHub {
      owner = "prettier";
      repo = "plugin-ruby";
      rev = "v4.0.4";
      fetchSubmodules = false;
      sha256 = "sha256-gEgs2L7q6WX/Cwtf4hsFzKZeJs2oXBckfQxINq2/Ahg=";
    };
    dontYarnBuild = "yes";
    pkgmgr = "yarn";
  };
  prettier-plugin-sh = {
    pname = "prettier-plugin-sh";
    version = "0.18.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/prettier-plugin-sh/-/prettier-plugin-sh-0.18.0.tgz";
      sha256 = "sha256-eAb2nZo1zNfykOn2LRQCYbjHIY0O/BOjmYZrRXLFUBM=";
    };
    extract = {
      "package.json" = ./. + "/sha256-eAb2nZo1zNfykOn2LRQCYbjHIY0O_BOjmYZrRXLFUBM=/package.json";
    };pkgmgr = "npm";
    dontNpmBuild = "yes";
    needGenLock = "yes";
  };
  prettier-plugin-sql = {
    pname = "prettier-plugin-sql";
    version = "0.20.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/prettier-plugin-sql/-/prettier-plugin-sql-0.20.0.tgz";
      sha256 = "sha256-2RSzk9YnUHovc1GAJu360W3VeEyaUEEh9fT9RqZgFNA=";
    };
    extract = {
      "package.json" = ./. + "/sha256-2RSzk9YnUHovc1GAJu360W3VeEyaUEEh9fT9RqZgFNA=/package.json";
    };pkgmgr = "npm";
    dontNpmBuild = "yes";
    needGenLock = "yes";
  };
  prettier-plugin-toml = {
    pname = "prettier-plugin-toml";
    version = "2.0.6";
    src = fetchurl {
      url = "https://registry.npmjs.org/prettier-plugin-toml/-/prettier-plugin-toml-2.0.6.tgz";
      sha256 = "sha256-TSG3iCwXcOjxbar7zWtey+JU9XPoSrenDOtU1abCo20=";
    };
    extract = {
      "package.json" = ./. + "/sha256-TSG3iCwXcOjxbar7zWtey+JU9XPoSrenDOtU1abCo20=/package.json";
    };pkgmgr = "npm";
    dontNpmBuild = "yes";
    needGenLock = "yes";
  };
  prettier-plugin-xml = {
    pname = "prettier-plugin-xml";
    version = "v3.4.1";
    src = fetchFromGitHub {
      owner = "prettier";
      repo = "plugin-xml";
      rev = "v3.4.1";
      fetchSubmodules = false;
      sha256 = "sha256-7/0a00fdDso8yZyFkrBUwA2uxlN/pifSrKHGDjJS5Y0=";
    };
    dontYarnBuild = "yes";
    pkgmgr = "yarn";
  };
}
