# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  zotero-better-bibtex = {
    pname = "zotero-better-bibtex";
    version = "7.0.62";
    src = fetchurl {
      url = "https://github.com/retorquere/zotero-better-bibtex/releases/download/v7.0.62/zotero-better-bibtex-7.0.62.xpi";
      sha256 = "sha256-MrJMj+BlzGY4qdxmlcLGaT5XkNrlVrh4HZ5bulEqWm0=";
    };
    addonId = "better-bibtex@iris-advies.com";
    license = "mit";
    homepage = "https://github.com/retorquere/zotero-better-bibtex";
    description = "Make Zotero effective for us LaTeX holdouts";
  };
  zotero-night = {
    pname = "zotero-night";
    version = "0.4.23";
    src = fetchurl {
      url = "https://github.com/tefkah/zotero-night/releases/download/v0.4.23/night.xpi";
      sha256 = "sha256-szoKwmYMm9fZrWxqN2ZJptahCgGkIUNwR0n3m5zhiJw=";
    };
    addonId = "night@tefkah.com";
    license = "gpl3";
    homepage = "https://github.com/tefkah/zotero";
    description = "Night theme for Zotero UI and PDF";
  };
  zotero-pdf-translate = {
    pname = "zotero-pdf-translate";
    version = "2.3.15";
    src = fetchurl {
      url = "https://github.com/windingwind/zotero-pdf-translate/releases/download/v2.3.15/translate-for-zotero.xpi";
      sha256 = "sha256-Dq+QmQTaURhHZDy2N2Ftkri/RGnUx/9I1tNNsYA7UQg=";
    };
    addonId = "zoteropdftranslate@euclpts.com";
    license = "agpl3Only";
    homepage = "https://github.com/winidngwind/zotero-pdf-translate";
    description = "Translate PDF, EPub, webpage, metadata, annotations, notes to the target language. Support 20+ translate services.";
  };
  zotero-reading-list = {
    pname = "zotero-reading-list";
    version = "1.5.14";
    src = fetchurl {
      url = "https://github.com/Dominic-DallOsto/zotero-reading-list/releases/download/v1.5.14/zotero-reading-list.xpi";
      sha256 = "sha256-ackaE5BpiyKJw98qsVdJpKAieogWwjeQ4mS+LSq+Ghg=";
    };
    addonId = "reading-list@hotmail.com";
    license = "gpl3";
    homepage = "https://github.com/Dominic-DallOsto/zotero-reading-list";
    description = "Keep track of whether you've read items in Zotero";
  };
  zotero-scipdf = {
    pname = "zotero-scipdf";
    version = "1.3.0";
    src = fetchurl {
      url = "https://github.com/syt2/zotero-scipdf/releases/download/V1.3.0/sci-pdf.xpi";
      sha256 = "sha256-Z0OVtN7JHmvfE0hZ6rQ6VUgLFJPF3hnewJn/iQ+Ma8c=";
    };
    addonId = "scipdf@ytshen.com";
    license = "agpl3Plus";
    homepage = "https://github.com/syt2/zotero-scipdf";
    description = "Download PDF from Sci-Hub automatically (For Zotero7)";
  };
  zotero-zotfile = {
    pname = "zotero-zotfile";
    version = "5.1.2";
    src = fetchurl {
      url = "https://github.com/jlegewie/zotfile/releases/download/v5.1.2/zotfile-5.1.2-fx.xpi";
      sha256 = "sha256-vmJVLqNgxbI6eE3TqDKJs/u/Bdemag2aADfy8L89YKc=";
    };
    addonId = "zotfile@columbia.edu";
    license = "gpl3";
    homepage = "https://github.com/jlegewie/zotfile";
    description = "Zotero plugin to manage your attachments: automatically rename, move, and attach PDFs (or other files) to Zotero items, sync PDFs from your Zotero library to your (mobile) PDF reader (e.g. an iPad, Android tablet, etc.), and extract PDF annotations.";
  };
  zotero-zotmoov = {
    pname = "zotero-zotmoov";
    version = "1.2.24";
    src = fetchurl {
      url = "https://github.com/wileyyugioh/zotmoov/releases/download/1.2.24/zotmoov-1.2.24-fx.xpi";
      sha256 = "sha256-77wLfqMv26C7SxXwmyOtiPjyFJb0xYcoj2m5hJzt+6c=";
    };
    addonId = "zotmoov@wileyy.com";
    license = "gpl3Only";
    homepage = "https://github.com/wileyyugioh/zotmoov";
    description = "Mooves attachments and links them";
  };
}
