{
  lib,
  writeShellScript,
  fetchFromGitHub,
  nix,
  nix-update,
  nodejs,
  buildNpmPackage,
  gnugrep,
  python3,
  coreutils,
  git,
}:
let
  pname = "mcpvault";

  # The upstream package-lock.json is generated by bun and omits `resolved` /
  # `integrity` for most entries (including zod, a runtime dependency of the
  # @modelcontextprotocol SDK). prefetch-npm-deps skips those, so `npm ci
  # --offline` fails with ENOTCACHED. Replace it with a fully-resolved lockfile
  # (regenerated via `npm install --package-lock-only`). This also runs inside
  # the fetchNpmDeps derivation (it inherits postPatch), keeping src and the
  # dependency cache consistent.
  packageLock = ./package-lock.json;

  updateScript = writeShellScript "mcpvault-update-script" ''
    export PATH=${lib.makeBinPath [
      nix
      nix-update
      nodejs
      gnugrep
      python3
      coreutils
      git
    ]}:$PATH
    ${builtins.readFile ./update.sh}
  '';
in
buildNpmPackage {
  inherit pname;
  version = "0-unstable-2026-08-26";
  src = fetchFromGitHub {
    owner = "bitbonsai";
    repo = pname;
    rev = "c5abeda9bed11864079f70ae7f33d134e294aad2";
    sha256 = "sha256-K7MCnTBOtNYzJT1zz4v3H9y+N2lE1+S2xi8BNUXDEl0=";
  };

  postPatch = ''
    cp ${packageLock} package-lock.json
  '';

  npmDepsFetcherVersion = 2;
  npmDepsHash = "sha256-STsZJifwgiqx5/Kg2/KkOq+8Tv/k1fmERzt61axt7hI=";
  npmFlags = [ "--legacy-peer-deps" ];
  makeCacheWritable = true;

  passthru.updateScript = {
    command = updateScript;
    attrPath = "mcpvault";
  };

  meta = {
    description = "A lightweight Model Context Protocol (MCP) server for safe Obsidian vault access";
    homepage = "https://github.com/bitbonsai/mcp-obsidian";
    mainProgram = "mcp-obsidian";
    lisense = lib.licenses.mit;
    platforms = [
      "x86_64-linux"
      "aarch64-linux"
      "aarch64-darwin"
    ];
  };
}
