[jupynium]
src.pypi = "jupynium"
fetch.pypi = "jupynium"

[valkey-glide]
src.pypi = "valkey-glide"
fetch.url = "https://pypi.org/packages/source/v/valkey-glide/valkey_glide-$ver.tar.gz"
cargo_lock = ["Cargo.lock"]

[version-pioneer]
src.pypi = "version-pioneer"
fetch.pypi = "version_pioneer"

[virtualsmartcard]
src.github_tag = "frankmorgner/vsmartcard"
src.regex = "virtualsmartcard-*"
fetch.github = "frankmorgner/vsmartcard"
