name: push cachix
on:
  push:
    branches:
      - main

permissions: read-all

jobs:
  push-cachix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dorny/paths-filter@v4
        id: change
        with:
          base: ${{ github.ref }}
          filters: |
            nix:
              - "**.nix"
              - "flake.lock"

      - uses: wimpysworld/nothing-but-nix@main
        if: steps.change.outputs.nix == 'true'
        with:
          hatchet-protocol: "rampage" # Options: holster, carve, cleave (default), rampage
          root-safe-haven: "8192"

      - uses: DeterminateSystems/nix-installer-action@v21
        with:
          extra-conf: |
            accept-flake-config = true
            connect-timeout = 15
            cores = 4
            http-connections = 25
            max-jobs = 1
            stalled-download-timeout = 15

      - uses: DeterminateSystems/magic-nix-cache-action@main

      - uses: cachix/cachix-action@v16
        if: steps.change.outputs.nix == 'true'
        with:
          name: misumisumi
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build check
        if: steps.change.outputs.nix == 'true'
        run: nix run github:Mic92/nix-fast-build  -- --no-link --no-nom
