name: update repository
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: "0 17 30 * 5" # runs weekly on Saturday at 02:30 (JST)

permissions: read-all

jobs:
  update-repo:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'misumisumi'
    steps:
      - uses: actions/checkout@v6

      - uses: actions/create-github-app-token@v3
        id: generate-token
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - uses: DeterminateSystems/nix-installer-action@v22
        with:
          extra-conf: |
            accept-flake-config = true
            connect-timeout = 15
            cores = 4
            download-buffer-size = 524288000
            http-connections = 25
            max-jobs = 2
            stalled-download-timeout = 15

      - name: Setup git account
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Update package version
        timeout-minutes: 60
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          nix run .#update-pkgs -- --commit

      - name: Update README
        run: |
          scripts/update-readme.sh
          git add README.md

      - uses: DeterminateSystems/update-flake-lock@v28
        id: update
        with:
          token: ${{ steps.generate-token.outputs.token }}
          commit-msg: "chore(flake.lock): auto update flake.lock"
          pr-title: "chore(flake.lock): auto update flake.lock" # Title of PR to be created
          pr-labels: | # Labels to be set on the PR
            dependencies
            automated
